server:
  port: 8040
spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/MrGlory/spring-cloud-simple/
          search-paths: cloud-config
          username: 
          password: 